config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :users, except: [:index, :edit, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/admin/users', to: "admin/users#index"
  get '/admin/edit/:id', to: "admin/users#edit"
  patch '/admin/edit/:id', to: "admin/users#do_edit"
  delete '/admin/destroy/:id', to: "admin/users#destroy"
  get '/login', to: "users#login"
  post '/login', to: "users#do_login"
  get '/logout', to: "users#logout"

  root 'users#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  validates_uniqueness_of :name, case_sensitive: false

  def password=(password)
    self.password_hash = BCrypt::Engine.hash_secret(password, '$2a$10$WwIq1tQTEKW6kb9T5OMiE.')
  end

  def self.login(user, password)
    hash = BCrypt::Engine.hash_secret(password, '$2a$10$WwIq1tQTEKW6kb9T5OMiE.')

    User.where("password_hash = '#{hash}' AND name = '#{user}'").first
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :do_edit, :destroy]
  before_action :check_admin

  def index
    @users = User.all
  end

  def edit
  end

  def do_edit
    @user.update!(user_params)

    if @user.save
      redirect_to action: "index"
    else
      flash.alert = "Errors: #{@user.errors.full_messages.to_sentence}"
      redirect_to "#{admin_edit_path}/#{@user.id}"
    end
  end

  def destroy
    @user.destroy

    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def check_admin
      unless session[:user_id]
        flash.alert = "You need to log in to see this page"
        redirect_to login_path
      else
        @logged_in_as = User.find(session[:user_id])

        unless @logged_in_as.admin?
          flash.alert = "Admin privs required"
          redirect_to login_path
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :favourite_color, :admin)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :check_logged_in

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    raise ActiveRecord::RecordNotFound if @blog.user != @user && @blog.private?
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    raise ActiveRecord::RecordNotFound unless @blog.user == @user
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = @user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    raise ActiveRecord::RecordNotFound unless @blog.user == @user

    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    raise ActiveRecord::RecordNotFound unless @blog.user == @user
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def check_logged_in
      unless session[:user_id]
        flash.alert = "You need to log in to see this page"
        redirect_to login_path
      else
        @user = User.find(session[:user_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:body, :title, :user_id, :private)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to controller: :blogs, action: :index
    else
      flash.alert = "Errors: #{@user.errors.full_messages.to_sentence}"
      redirect_to action: "new"
    end
  end

  def login
    if session[:user_id]
      redirect_to controller: :blogs, action: :index
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to action: :login
  end

  def do_login
    @user = User.find_by(name: user_params[:name])
    if @user&.log_in(user_params[:password])
      session[:user_id] = @user.id
      redirect_to controller: :blogs, action: :index
    else
      flash.alert = "Name or password not found."
      redirect_to "/login"
    end

  rescue ActiveRecord::RecordNotFound
    flash.alert = "Name or password not found."
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :favourite_color)
    end

    def login_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if flash[:alert] %>
  <p style="background-color: red;">
    <%= flash[:alert] %>
  </p>
<% end %>

<%= form_with(model: user, url: "/admin/edit/#{user.id}", local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :favourite_color %>
    <%= form.text_field :favourite_color, id: :user_favourite_color %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin, id: :user_admin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password hash</th>
      <th>Favourite color</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_hash %></td>
        <td><%= user.favourite_color %></td>
        <td><%= user.admin? %></td>
        <td><%= link_to 'Edit', "/admin/edit/#{user.id}" %></td>
        <% unless @logged_in_as == user %>
        <td><%= link_to 'Destroy', "/admin/destroy/#{user.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :blog_body %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private, id: :blog_private %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hi <%= @user.name %>! Here are the posts you can see:</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Title</th>
      <th>User</th>
      <th>Private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <% if blog.user == @user || !blog.private? %>
        <tr>
          <td><%= blog.body %></td>
          <td><%= blog.title %></td>
          <td><%= blog.user.name %></td>
          <td><%= blog.private? %></td>
          <td><%= link_to 'Show', blog %></td>
          <% if blog.user == @user %>
            <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
            <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>
<%= link_to 'Logout', "/logout" %>
<% if @user.admin? %>
  <%= link_to 'Admin', '/admin/users' %>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>

<p>
  <%= @blog.body %>
</p>

<%= link_to "Back", "/blogs" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Badrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if flash[:alert] %>
  <p style="background-color: red;">
    <%= flash[:alert] %>
  </p>
<% end %>

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :favourite_color %>
    <%= form.text_field :favourite_color, id: :user_favourite_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/login.html.erb
<% if flash[:alert] %>
  <p style="background-color: red;">
    <%= flash[:alert] %>
  </p>
<% end %>

<%= form_tag(action: "do_login") do %>
  <div class="field">
    <%= label_tag(:name) %>
    <%= text_field_tag("user[name]") %>
  </div>

  <div class="field">
    <%= label_tag(:password) %>
    <%= password_field_tag "user[password]" %>
  </div>

  <div class="actions">
    <%= submit_tag "Submit" %>
  </div>
<% end %>

<%= link_to "New account", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>